stat_icon_list = { # Ubicación de los iconos correspondientes a las estadisticas
    "Gold":                         "src/Vista/Assets/Images/StatIcon/Gold_icon.png",
    "Health":                       "src/Vista/Assets/Images/StatIcon/Health_icon.png",
    "Health Growth":                "src/Vista/Assets/Images/StatIcon/Health_icon.png",
    "Health Regen":                 "src/Vista/Assets/Images/StatIcon/Health_regeneration_icon.png",
    "Health Regen Growth":          "src/Vista/Assets/Images/StatIcon/Health_regeneration_icon.png",
    "Mana":                         "src/Vista/Assets/Images/StatIcon/Mana_icon.png",
    "Mana Growth":                  "src/Vista/Assets/Images/StatIcon/Mana_icon.png",
    "Mana Regen":                   "src/Vista/Assets/Images/StatIcon/Mana_regeneration_icon.png",
    "Mana Regen Growth":            "src/Vista/Assets/Images/StatIcon/Mana_regeneration_icon.png",
    "Energy":                       "src/Vista/Assets/Images/StatIcon/Energy_icon.png",
    "Energy Regen":                 "src/Vista/Assets/Images/StatIcon/Energy_regeneration_icon.png",
    "Attack Damage":                "src/Vista/Assets/Images/StatIcon/Attack_damage_icon.png",
    "Attack Damage Growth":         "src/Vista/Assets/Images/StatIcon/Attack_damage_icon.png",
    "Ability Power":                "src/Vista/Assets/Images/StatIcon/Ability_power_icon.png",
    "Attack Speed(%)":              "src/Vista/Assets/Images/StatIcon/Attack_speed_icon.png",
    "Base Attack Speed":            "src/Vista/Assets/Images/StatIcon/Attack_speed_icon.png",
    "Attack Speed Ratio":           "src/Vista/Assets/Images/StatIcon/Attack_speed_icon.png",
    "Bonus Attack Speed":           "src/Vista/Assets/Images/StatIcon/Attack_speed_icon.png",
    "Armor":                        "src/Vista/Assets/Images/StatIcon/Armor_icon.png",
    "Armor Growth":                 "src/Vista/Assets/Images/StatIcon/Armor_icon.png",
    "Magic Resistance":             "src/Vista/Assets/Images/StatIcon/Magic_resistance_icon.png",
    "Magic Resistance Growth":      "src/Vista/Assets/Images/StatIcon/Magic_resistance_icon.png",
    "Range":                        "src/Vista/Assets/Images/StatIcon/Range_icon.png",
    "Heal & Shield Power(%)":       "src/Vista/Assets/Images/StatIcon/Heal_and_shield_power_icon.png",
    "Tenacity":                     "src/Vista/Assets/Images/StatIcon/Tenacity_icon.png",
    "Critical Strike Chance(%)":    "src/Vista/Assets/Images/StatIcon/Critical_strike_chance_icon.png",
    "Critical Strike Damage(%)":    "src/Vista/Assets/Images/StatIcon/Critical_strike_damage_icon.png",
    "Lethality":                    "src/Vista/Assets/Images/StatIcon/Armor_penetration_icon.png",
    "Armor Penetration(%)":         "src/Vista/Assets/Images/StatIcon/Armor_penetration_icon.png",
    "MagicResist Flat Penetration": "src/Vista/Assets/Images/StatIcon/Magic_penetration_icon.png",
    "MagicResist Penetration(%)":   "src/Vista/Assets/Images/StatIcon/Magic_penetration_icon.png",
    "Lifesteal(%)":                 "src/Vista/Assets/Images/StatIcon/Life_steal_icon.png",
    "Ability Haste":                "src/Vista/Assets/Images/StatIcon/Cooldown_reduction_icon.png",
    "Movement Speed":               "src/Vista/Assets/Images/StatIcon/Movement_speed_icon.png",
    "Movement Speed(%)":            "src/Vista/Assets/Images/StatIcon/Movement_speed_icon.png",
}